### ISSUE TITLE
(<|>) and mplus are not associative

### ISSUE THREAD

**Issue by purefn** [michaelt/streaming#15]
Consider the following

```
λ> let a = return "a" :: S.Stream (Of String) Identity String
a :: Stream (Of String) Identity String
λ> let b = return "b" :: S.Stream (Of String) Identity String
b :: Stream (Of String) Identity String
λ> let c = return "c" :: S.Stream(Of String) Identity String
c :: Stream (Of String) Identity String
λ> (a <|> b) <|> c
Effect (Identity (Return "c"))
it :: Stream (Of String) Identity String
λ> a <|> (b <|> c)
Effect (Identity (Return "a"))
it :: Stream (Of String) Identity String
```

This suggests that the `Alternative` and `MonadPlus` instances do not obey the laws.

**Comment by michaelt** [comment]
Wow, sure does!  I remember changing the Alternative instance when I realized the one from FreeT was wrong, and this one was right. The Alternative instance here presupposes that `f` in `Stream f m` is Applicative, and zips them together step by step; thus `empty` is supposed to be a sort of infinite delay of pure (pure pure ..))  But I must have implemented it wrong -- or else the idea was wrong.  I will look now.

**Comment by michaelt** [comment]
The defect was in the implementation of `zipsWith`. It was a typical case of the illusions that can come from inspecting the streams by naive pattern matching on the (hidden) constructors, rather than hygenically using `inspect`.  The instance wants the return value of `p <|> q` to be the return value of whichever stream ends first -- but then in the case where the are both returning at once, and the race is tied, to be biased toward the left. But the way I wrote it, it was assumed that a stream would only have no `f` layers ahead and be headed to the 'done' state, if it had the shape: `(Return x)`. But on the quotient we mean to be perceptible to the user, this is equivalent to `Effect (return (Return x))` and things like that. And in fact this equivalence was used elsewhere in the definition. The result of  `p <|> q` was (and is) in all cases wrapped in `Effect`.  So in `(p <|> q) <|> r`, which gave the wrong answer, p <|> q certainly has `Effect ...` as its outermost constructor. And this, on the bad definition, in all cases lost to r, if _it_ had the form `Return xxx`.  But in your example `p <|> q` was in the done state, though not in the `Return xxx` shape, and should by rights have won the race.

The slightly irregular or out of kilter type, and hidden constructors, follow the pattern in `Pipes.Internal`; they are a bit of a nightmare to work with but the effect is always much faster than `FreeT`, which we are trying to emulate.  There is a trade off in implementing particular functions: direct use of the constructors tends to be faster, but tends to give rise to illusions in the implementor. 

Sorry, these remarks are probably totally obscure. Thanks very much for spotting the mistake!

**Comment by michaelt** [comment]
I uploaded it to Hackage as  streaming-0.1.4.3 Thanks again!

**Comment by purefn** [comment]
Glad to help! More glad that it was a straightforward fix.
