### ISSUE TITLE
Is it possible to have an inverse of `unzips`?

### ISSUE THREAD

**Issue by phischu** [michaelt/streaming#19]
The `zips` function takes two streams and zips them together. But I am looking for a function

```
ununzips :: (Monad m, Functor f, Functor g) => Stream f (Stream g m) r -> Stream (Compose f g) m r
```

How would I write such a function?

My use case is to copy a stream, act on the copy and then zip the two streams together:

```
usecase :: (Monad m) => Stream (Of Int) m r -> Stream (Compose (Of Int) (Of Bool)) m r
usecase = ununzips . hoist (map even) . copy
```

Thank you.

**Comment by michaelt** [comment]
I think the basic answer is no.  `ununzip` could be written, but would be like a `Data.List` function

```
ununzip :: [([a],b)] -> [(a,b)]
```

which would have to drop any `b` associated with an empty list of `a`s and then, seemingly arbitrarily, take the first or last `a`.   The trouble here is that you can't recover the connection without making assumptions about how the `[([a],b)]` was constructed.  In your particular case this would work, but a combinator

```
ununzip :: Monad m => Stream (Of a) (Stream (Of b) m) r -> Stream (Of (a,b)) m r 
ununzip :: Monad m => Stream (Of a) (Stream (Of b) m) r -> Stream (Compose (Of a) (Of b))) m r 
```

or the like, would probably give a wrong impression.

By the way, probably your intention might be clearer if you wrote `S.map even . copy` instead of `hoist (S.map even)`.   `copy` gives you a stream of `a`s which are copies of `a` being yielded in (what is now) the underlying monad. As far as the type goes,  we here have a stream of `Bool`s separated by some number of yields of `Int`s. In fact _in this case_ each `Bool` is preceded by the yield of exactly one `Int`, the one presupposed in calculating it. In the signature `Stream f m r`, the `m` actions precede the `f` things, which is a little annoying but required by the monad transformer setup. (I found it confusing at first).  Intuitively, here, the integers should 'come first' and the booleans second.  

Were you thinking about this in connection with the "uniqhash"/MealyM [post](https://www.reddit.com/r/haskell/comments/5bf4gf/uniqhash_machines_implementation_using_mealym/)?

**Comment by phischu** [comment]
Thank you for the prompt and clear reply. Yes, I have implemented "uniqhash" with `streaming`, and it turned out very nice except for this thing. You can take a look at it [here](https://gist.github.com/phischu/2bc7a8c811ed9598a4d4603b6cae8f2f). I want to show it to the "uniqhash" author for comparison. Again thank you, you can close the issue.

**Comment by michaelt** [comment]
Thanks! The program does look great.  

I will think about writing a `rezip` or something like it. I would like to write some more tutorial material where stuff like `copy` `partition` `unseparate` , maybe `rezip` etc.  are discussed -  i.e. where you put stuff on the inner monad and work on some aspect of the 'outer' stream before returning.  A lot of what sordina is calling graphs can appear in this. `rezip` is a somewhat special case.   Of course, you can do all this with pipes and conduit, but somehow the tutorials make it seem more complicated than it actually is.
