### ISSUE TITLE
Strange behavior from S.head_

### ISSUE THREAD

**Issue by afcady** [michaelt/streaming#25]
I wrote some code similar to the documentation example for `partitionEithers`:

    >>> S.toList $ S.print $ S.take 2 $
                   partitionEithers $ S.map readEither $
                   S.stdinLn  :: IO (Of [Int] ())

...except I only wanted one `Left`.  I tried using `S.head_` instead of `S.take 1`, but that caused the whole input stream to be consumed instead of stopping after the first `Left`.

I used this instead:

```
streamHead :: Monad m => Stream (Of a) m r -> m (Maybe a)
streamHead = fmap listToMaybe . S.toList_ . S.take 1
```

...which has the same type signature as `S.head_` but, to my mind anyway, the expected behavior.

Maybe it's intentional that `S.head_` does not behave like that already.  But it strikes me as at least counterintuitive/in need of documentation.

**Comment by michaelt** [comment]
Yes I think `head_` is not rational, now that you mention it. There was a little too much mechanism in the `somefunction`/`somefunction_`  relation. The corresponding function `head` however is correct, it must go through the whole stream in order to recover the final value. This is a condition of mapping. 

     >>> S.toList_ $ S.concat $  mapsM S.head $ S.group $ S.take 5 $ (S.readLn @IO @Int)
     1<Enter>
     1<Enter>
     2<Enter>
     2<Enter>
     3<Enter>
    [1,2,3]

if `head` lost the rest of the stream we couldn't do this.

**Comment by michaelt** [comment]
I emended it, so it'll be in the next version I upload to hackage. Where there is a `func/func_` distinction I am thinking of the operation as a left fold. The ones without underscores are "standard" because mappable and you can replace them with the reified folds in `Control.Foldl` replacing

     func str

with 

    L.purely S.fold L.func str

and then start composing them with others


    L.purely S.fold (liftA3 (,,) L.func L.sum L.product) str

In that case there is no question of 'early exit'.  It is supposed to be an advantage of the uncomposable `func_` folds in `Streaming.Prelude`, though, that they exit early if that is a possibility - so others like `all_` and `elem_` are correctly implemented here, but `head_` wasn't.  It might be that this is a survival of the first version of this library where I was still trying to figure out the rational way of handling these cases and at first had a `foo/foo'` distinction, if I remember, where the extra `'` meant that the fold carried the return value and was mappable. Then I decided that the right path was to 'privilege' the folds with the final return value as the true 'rank 2' mappings or 'natural transformations' -- and so `foo'` became `foo` and `foo` became `foo_` (the underscore signalling that it's missing something!)

**Comment by afcady** [comment]
Thanks, looks good.
