### ISSUE TITLE
hoist is wrong

### ISSUE THREAD

**Issue by treeowl** [michaelt/streaming#32]
`pipes` goes to some inefficient trouble to make sure `hoist` works right when applied to a function that's not a monad morphism. I believe that `streaming` fails to account for this. In particular, the transformation is applied separately to each `Effect`, rather than to their combination. Gabriel Gonzalez seems to think that `FreeT` gets this right automatically but inefficiently; I don't know details.

**Comment by treeowl** [comment]
Indeed, there is a real problem:

```haskell
bloop, blaap :: Stream (Of Char) [] Char
bloop = hoist (\x -> x ++ x) (lift "ab" >>= lift . (: []))
blaap = hoist (\x -> x ++ x) (lift ("ab" >>= (: [])))
```

According to the `MonadTrans` laws, `bloop` and `blaap` should be equal. But 

```haskell
toList bloop =
  ["" :> 'a',"" :> 'a',"" :> 'b',"" :> 'b',"" :> 'a',"" :> 'a',"" :> 'b',"" :> 'b']
```

while

```haskell
toList blaap =
  ["" :> 'a',"" :> 'b',"" :> 'a',"" :> 'b'] 
```

**Comment by treeowl** [comment]
One could, I think, argue that using `hoist` with something that's not a monad morphism is altogether wrong anyway, but the documentation on that is unclear. However, there are other functions that are definitely trouble:

```haskell
foo, bar :: Stream (Of Char) [] Char
foo = lift ['a','b'] >>= lift . (: [])
bar = lift (['a','b'] >>= (: []))
```

Then `destroy foo P.show P.show P.show /= destroy bar P.show P.show P.show`. I blame `destroy`, which should probably be in `.Internal`.

**Comment by treeowl** [comment]
@Gabriel439 may have thoughts on these issues.

**Comment by Gabriella439** [comment]
The way `pipes` approaches this problem is to provide an `unsafeHoist` function which is more efficient.  The tradeoff between the two is that:

* `unsafeHoist` is faster, but allows you to detect a monad morphism law violation if you supply an argument to `unsafeHoist` that is not a monad morphism
* `hoist` is slower, but does not allow you to detect a monad morphism law violation

Another approach is to keep `hoist` as the efficient version, but tell users that they have to provide a monad morphism as the argument, and if they don't then it's their fault if anything goes wrong

The reason I went with the first approach is that it's no slower than encoding the `Proxy` type in terms of `FreeT`, and often much faster (if you don't use `hoist` or you use `unsafeHoist`)

`hoist` was designed to only accept monad morphisms as its argument, but there is no easy way to enforce that in Haskell.  If we could enforce the rule then there would be no need for `hoist` vs `unsafeHoist`

See also the documentation in `Pipes.Internal`:

https://hackage.haskell.org/package/pipes-4.3.4/docs/Pipes-Internal.html

**Comment by treeowl** [comment]
@Gabriel439 I suggest that you update the documentation for `MFunctor` to indicate that `hoist` may *only* be used with a monad morphism. That will give library authors explicit permission to do broken things when it's not.

**Comment by treeowl** [comment]
I'll close this, thanks to the documentation change in `mmorph`. I'll open a new issue or PR for the `destroy` problem.
