### ISSUE TITLE
Group examples

### ISSUE THREAD

**Issue by AlexeyRaga** [michaelt/streaming#4]
First, thank you for the great lib!

Could you please quickly explain how `group`/`groupBy` combinators can be used?

The `group` return type is `Stream (Stream (Of a) m) m r` so I can't use "normal" `map` with it.

I tried using `maps`:

```
let s = S.take 10 $ S.iterate (+1) 0
let g = S.group s --just to have some groups

:t S.maps (S.fold_ (+) 0 id) g
Couldn't match type ‘x’ with ‘Integer’
  ‘x’ is a rigid type variable bound by
      a type expected by the context: S.Stream (S.Of Integer) g x -> g x
```

I had similar issues when using `fold`, `toList` etc. 
I clearly miss something here, so what would be the way to map over a grouped stream and to do something with inner streams? 

For simplicity we can assume that the task would be to batch a stream somehow and to operate on individual batches?

Thanks!

**Comment by AlexeyRaga** [comment]
I see that the tests/examples in the `Prelude.hs` use `group` and `breaks` with `mapsM`, but `mapsM` combinator is defined in `Internal` and is not exposed by `Prelude`. Is it a missing export?

**Comment by michaelt** [comment]
`mapsM` is exported by Streaming itself so it should be enough to add `import Streaming`.  

But the other problem is that when you are somehow folding or collapsing each subgroup, you need to keep the information about _the rest of the sequence_, so you you should be using `fold` rather than `fold_`.   You use `fold_` (and the concrete folds like `sum_`, `length_` etc.) when the return value of the stream you are folding over is irrelevant to you. The underscore is supposed to represent the thowing away of information, as in `Prelude.mapM_`, `Prelude.sequence_` and so on. But when mapping a fold over each subsequence of a `Stream (Stream ..)`, you need to retain the connectedness of the stream, so you need the no-underscore versions `fold` `sum`, etc. -- if you think about how the folding proceeds, the "extra information" in the return value of the fold, is in fact the rest of the stream of streams you are folding over successively.  `mapsM` rather than `maps` is usually what you need for mapping a fold over subsegments, since the result type you are getting from each section of folding, tends to be in the monad :: `sum :: Stream (Of Int) IO r -> IO (Of Int r)`  

```
> let s = S.take 10 $ S.iterate (+1) 0
> let g = S.group s
> S.print $ mapsM (S.toList) g
[0]
[1]
[2]
[3]
[4]
[5]
[6]
[7]
[8]
[9]
> S.print $ mapsM (S.fold (+) 0 id) g
0
1
2
3
4
5
6
7
8
9
> let p = S.each "Mississippi"
> let q = S.group p
> S.print $ mapsM S.toList q
"M"
"i"
"ss"
"i"
"ss"
"i"
"pp"
"i"
```

Maybe I should re-export mapsM in the the Prelude also, but I was trying to keep "functor general" things in Streaming; on the other hand, it's a pain in the neck to have to think what's where. One sign that something is in the general `Streaming` module, is, if it is like a prelude expression, it will include an additional 's', as in `maps` `mapsM` `groups` (here I am following something from `pipes-group`, perhaps carrying it too far.) 

Thanks for looking into it!

**Comment by AlexeyRaga** [comment]
Thank you very much for a detailed explanation!

As for `mapsM` - it was me being stupid and only importing `Streaming.Prelude` but not `Streaming`.

I'll close this issue because I have my answers.
