### ISSUE TITLE
Streaming lists doesn't stream

### ISSUE THREAD

**Issue by echatav** [michaelt/streaming#8]
Hi, sorry if this question is too basic for an issue. How come this tries to load the whole stream into memory instead of using constant space?

``` haskell
print =<< S.fold_ (zipWith (\n _ -> n+1)) (replicate 5 0) id (S.replicate 100000000 (replicate 5 3.14))
```

**Comment by michaelt** [comment]
A fold like `S.fold` or `S.fold_` is a strict left fold, like `Data.List.foldl'`. In particular, it will always work through the entire stream it is given, and only has a result when it has consumed. In this case you are building a list from seed by iterating over a stream of lists, zipping with one after another. The reason why the memory use is going wrong here is that the arguments to `S.fold_` are not strict, and really can't be since the folding function is `[Int] -> [a] -> [Int]`. 

If I write instead something like

```
import Streaming
import qualified Streaming.Prelude as S

main = do 
  ns <- S.fold_ (\n ls -> n + length ls) 0 id 
            (S.replicate 100000000 (replicate 3 3.14))  
  print ns
```

which sums the lengths of all the input lists, then the memory use is the same whatever I put in the position of `100000000` .  I see `1236K` in `top`

You should be able to reproduce this using `foldl'` from Data.List.   ... In fact here it is

```
import Data.List (foldl')
main = print $ foldl' (zipWith (\n _ -> n+1)) (replicate 5 0)  
                      (replicate 100000000 (replicate 5 3.14))
```

this accumulates like crazy, while the corresponding strict fold-function is able to update the seed 0 step by step.

I'm not sure I'm being clear. What do you think?

**Comment by echatav** [comment]
Hmmm, I managed to solve it by changing my update function to `deepseq` the state.

``` haskell
print =<< S.fold_ (\st -> deepseq st (zipWith (\n _ -> (n::Int)+1) st)) (replicate 5 0) id (S.replicate 100000000 (replicate 5 3.14))
```

It's still not clear to me how evaluation is working and why `deepseq` fixes the leak.

**Comment by michaelt** [comment]
Here's a different version of the original program

```
import Streaming
import qualified Streaming.Prelude as S
import qualified Data.Vector.Unboxed as U

main = do
  ns <- S.fold_ (U.zipWith (\n _ -> n+1)) (U.replicate 5 (0::Int)) U.toList
            (S.replicate 100000000 (U.replicate 5 (3.14::Double)))
  print ns
```

It just uses `1104K` since `U.zipWith` is able to update the seed vector strictly.  I think the way to describe the list version, is that there `S.fold_` is only managing to build a giant Haskell expression; the call to `print` then forces it to be evaluated.

**Comment by michaelt** [comment]
Oh I missed the message about deepseq, but yes, it does the equivalent to my translation into unboxed vectors, but without the translation. Here's a version where the input stream contains lists, and the printed output is a list, but operations are strictified in the middle by use of vectors

```
import Streaming
import qualified Streaming.Prelude as S
import qualified Data.Vector.Unboxed as U

main = do
  ns <- S.fold_ (U.zipWith (\n _ -> n+1)) (U.replicate 5 (0::Int)) U.toList
          $ S.map U.fromList 
          $ (S.replicate 100000000 (replicate 5 (3.14::Double)))
  print ns
```
